### ISSUE TITLE
images don't load

### ISSUE THREAD

**Issue by mk** [nextjournal/clerk-slideshow#3]
Since `webserver/blob->presented` now assumes a structure with a `:nextjournal/presented` key that doesn't apply to the slideshow viewer.

**Comment by dgtized** [comment]
```
(ns example-talk
  #:nextjournal.clerk{:visibility {:code :hide}}
  (:require
   [clojure.java.io :as io]
   [nextjournal.clerk :as clerk]
   [nextjournal.clerk-slideshow :as slideshow])
  (:import
   (javax.imageio ImageIO)))

;; ---
;; # Testing

^{::clerk/visibility {:result :hide}}
(comment
  (clerk/add-viewers! [slideshow/viewer])
  (clerk/reset-viewers! clerk/default-viewers))

(ImageIO/read (io/file "test-image.png"))
```

On first load this works correctly, but after evaluating the add-viewer line, it renders a broken image instead.

**Comment by zampino** [comment]
Fixed in Clerk with https://github.com/nextjournal/clerk/commit/0de032d53c796ed7296fbd56c1c57fa7ee8b0604.
