### ISSUE TITLE
Slideshow functionality is not working

### ISSUE THREAD

**Issue by aardvark** [nextjournal/clerk-slideshow#4]
When trying to setup slideshow functionality from the latest clerk (0.13.842) clerk fails with the error:
```
Unhandled java.io.FileNotFoundException
Could not locate nextjournal/clerk_slideshow__init.class, nextjournal/clerk_slideshow.clj or nextjournal/clerk_slideshow.cljc on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.
```
If I manually include clerk_slideshow in deps.edn like:
```
io.github.nextjournal/clerk-slideshow {:git/sha "562f634494a1e1a9149ed78d5d39fd9486cc00ba"}
```
the error goes away, but slideshow viewer is not working at all. 
Markdown line separators are shown as lines and no "slideshow" is happening.

I have also tried to manually cloning this repo and trying to run against a local clerk setup, but same error about classpath is shown. 
I am not sure how to proceed with this issue really.

**Comment by zampino** [comment]
> If I manually include clerk_slideshow in deps.edn like

yes, it's probably not clear from the README, but you have to include this library in your deps in order to require the slideshow viewer. With that in place you should be able to require it e.g. from the notebook namespace

```clj
(ns my-slideshow 
  (:require [nextjournal.clerk :as clerk]
            [nextjournal.clerk-slideshow :as clerk-slideshow]))

(clerk/add-viewers! [clerk-slideshow/viewer])
```

Note, you also need to call `clerk/add-viewers!` in order for it to have an effect.

**Comment by zampino** [comment]
In addition, using the latest version of this library might help. The one you pasted probably doesn't work in combination with the Clerk version you mentioned. This `deps.edn` setup actually works

```clj
 {:deps {io.github.nextjournal/clerk {:mvn/version "0.13.842"}
         io.github.nextjournal/clerk-slideshow {:git/sha "c7fcc3186790399e0f0090061c24c44200adb872"}}
```

Please reopen if that doesn't fix your issue.
